name: Make Repository Public

on:
  schedule:
    - cron: '29 14 19 1 *' # 在北京时间2025年1月19日0点执行任务（UTC时间2025年1月18日16点）

jobs:
  make-public:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make repository public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo edit ${{ github.repository }} --visibility public
